### ISSUE TITLE
Reset idle timer on game controller input

### ISSUE THREAD

**Issue by thetvliam** [bkbilly/lnxlink#104]
### Describe the solution you'd like

Have the idle timer reset when using a game controller like it does with keyboard an mouse input.

**Comment by bkbilly** [comment]
That's a really nice suggestion of a feature to have. 
I hadn't notice that the Gamepad doesn't reset the system idle time.
There are two projects that does this which I haven't tried if they work:
 - https://github.com/nowrep/wljoywake
 - https://github.com/foresto/joystickwake

I've also looked into creating my own module for LNXlink and it seems there is an issue on Ubuntu 24.04 with the XBOX controller using a Bluetooth connection.
I found a work around, but it's gonna be a bit more complicated. 
Hopefully I'll have it ready soon.

**Comment by thetvliam** [comment]
A module for this would be great 😃. I use the idle time and media info along with motion sensors as a really accurate room presence detection. But playing a game with a controller and not moving much bypasses all of these 😅

**Comment by bkbilly** [comment]
You could also make use of the `fullscreen`, `active_window` or `speaker_used` modules to get better results on your room presence.

**Comment by thetvliam** [comment]
Good idea 😁

**Comment by bkbilly** [comment]
I've pushed an update with the [gamepad](https://github.com/bkbilly/lnxlink/blob/master/lnxlink/modules/gamepad.py) module.
You can either download the new file and add it as a [custom module](https://bkbilly.gitbook.io/lnxlink/configuration#custom-module), or install the development version of LNXlink. On the next version it will be available by default.

It doesn't reset the idle time because it could have applications for other kind of automations.
If you need for the idle time to be reset, you can create an automation on Home Assistant that sends the `bash` command `xdotool key 0x00` every few seconds when the `Gamepad Used` sensor is active.

It should support any gamepad and finds them automatically when they connect/disconnect though on disconnection it shows some errors, but they are not important.

**Comment by thetvliam** [comment]
Just added it. Works great! Thank you 😊
