### ISSUE TITLE
Only report what changed

### ISSUE THREAD

**Issue by giggio** [bkbilly/lnxlink#117]
### Describe the solution you'd like

I see a lot of messages going through even though several of them did not change.
I'd like a way to optionally only send the ones that changed.

### Additional context

I'm concerned especially about the media thumbnail, which I'm getting a lot of change logs in the logbook, even though the image is the same. That does not happen to the other sensors.

When investigating the topics I noticed that all information is sent all the time, even though only the thumbnail shows the changed state log (not sure why).

**Comment by bkbilly** [comment]
Thank you for raising this issue with the thumbnail, as I hadn't noticed it.
By default the thumbnail is not enabled because if you are using the [hass-mqtt-mediaplayer](https://github.com/bkbilly/hass-mqtt-mediaplayer) then it is not needed.
I'll try to find a way to send it only when it is changed, so that if you need it, you will be able to enable it without overflowing the logbook.
In the meantime, you could safely disable it from Home Assistant.

As for the other sensors, this will be a bit more complicated.
Some of them can be converted to asynchronous calls which is not as easy to do and not feasible with all of them.

The sensors don't show up on logbook if there isn't any change, but the thumbnail is of type image which contains the time that it was updated. This is the reason why it has so many log events.

**Comment by giggio** [comment]
Great, I disabled the thumbnail sensor on HA and it still shows on hass-mqtt-mediaplayer! That is helpful for now.

Still, the PC floods the topics with information, I believe the issue still applies, even if the logbook is not showing the changes. :)

**Comment by bkbilly** [comment]
I looked into your idea and I found a universal way of updating the entities only when they have different values.

On the `config.yaml` file a new option will appear called `update_on_change`.
By default this is `false` which is the way it currently works and it will send the status for all the sensors.
If you change it to `true` it will send only the sensor values that have changed.

Keep in mind that by enabling this option and restart Home Assistant, the sensors will become unavailable.
This is because by default the `retain` option is `false` so it won't save the state of the sensors on the MQTT broker.

**Comment by giggio** [comment]
Interesting. What do you think of sending an update when it changes or when the timeout is about to expire, so they don't become unavailable? BTW, is that timeout configurable on the MQTT broker?

**Comment by bkbilly** [comment]
I am not sure I understand what you mean exactly.
There is no timeout period setting on MQTT broker, or my LNXlink application.

If you set the new option `update_on_change` to `true` then I would recommend setting the `retain` option to `true` as well, so that when the Home Assistant restarts, it won't have these options unavailable.

**Comment by giggio** [comment]
What I meant is how long until HA considers an entity unavailable. 5 minutes? 30 minutes? I don't know.

If I set `retain` to `true` and turn the computer off, it will show as available, incorrectly. So, I'd like a way to know when the PC is off, which I'd lose if I set `retain` to `true`.

So, instead, we could send the statuses when they change AND before the entity is about to become unavailable.

**Comment by giggio** [comment]
Oh, I just read [this](https://www.home-assistant.io/integrations/mqtt):

> A device or service can announce its availability by publishing a Birth message and set a Will message at the broker. When the device or service loses connection to the broker, the broker will publish the Will message. This allows the MQTT integration to make an entity unavailable.

Are you using that?
I'm sorry, I'm new to this. Then if that is true we don't need the "refresh" messages.

**Comment by giggio** [comment]
Ok, I just read the entire thing. How about these options:

1. An option to enable `retain` in the messages from `lnxlink`.
2. When `lnxlink` starts all information is sent, even if not changed. This would be a way to refresh a restarted broker.
3. I also thought of a way for HA to ask for an update. We could set this up as an automation, for example, after HA restarts an automation runs that sends an MQTT message to the PC, and then it sends all the messages, updating all entities.
4. Another option is to send all statuses every interval (x seconds) OR when changed.

**Comment by bkbilly** [comment]
All sensors become unavailable when the MQTT topic `lwt` has a value of `OFF`. This is also done automatically with the Will and Testament which is activated when it loses connection with the MQTT broker. No sensor is using timeout.

As for your suggestions:
1. There is an option for enabling or disabling the retain messages. You can find it on your configuration file under `mqtt->lwt->retain`.
2. With the new option I created, when LNXlink starts, it will send all the information, so it's already implemented.
3. You could force an update by creating a new custom module. All you need is to create a `start_control` method with the code: `self.lnxlink.prev_publish = {}`. Then you could send an MQTT topic to run this command.
4. To update the statuses every several seconds or minutes is a nice workaround and what most MQTT apps use. I'll consider implementing something like that.

**Comment by bkbilly** [comment]
I've released the new version 2024.8.0 with this feature.
