### ISSUE TITLE
Can send_keys be adapted for Wayland?

### ISSUE THREAD

**Issue by luizcorreia** [bkbilly/lnxlink#29]
The pynput requires sudo/root to work on wayland, because it uses uinput.

I found this app https://git.sr.ht/~geb/dotool that works everywhere. 
Or, would be a good ideia create a separated module for wayland?

**Comment by bkbilly** [comment]
It's a nice idea to replace the `send_keys` module with another which will also work as a headless installation.
The one you proposed needs to be build on the system, but there is an alternative which works really good.
This is the `xdotool` which supports many features like mouse movement and key presses.
You can try if it works for you on a terminal like so:
```bash
xdotool key ctrl+shift+t
```

**Comment by bkbilly** [comment]
Added on version `2022.11.4` of lnxlink the ability to run any command, so you can send the above command using mqtt.

**Comment by Iceman248** [comment]
Having my X11 break down after multi touch tapping the desktop (bizarre, I know), I have been at least using Wayland in the interim. I noticed send_keys has to have permission granted after each reboot, but soon after it doesn't work I don't seem to be able to get it to again unless I reboot. I read the following about using alternatives. I installed dotool (docs I used (https://git.sr.ht/~geb/dotool/tree/master/doc/dotool.1.scd) and it doesn't have these permission issues. I setup some bash commands in the config and they have been working well. I'm not suggesting you necessarily switch or add this since I resolved this particular issue, just wanted to share my solution.
