### ISSUE TITLE
Use nvidia-settings for GPU load if nvsmi load is NaN

### ISSUE THREAD

**Issue by PW999** [bkbilly/lnxlink#69]
### Describe the solution you'd like

I'm running a GTX770 using the 470 drivers on Manjaro. For some reasons, nvidia-smi doesn't properly report the GPU utilization. In fact, a lot of stuff that's supported by the card doesn't properly work with nvidia-smi, so I'm assuming this might be an issue for all older generations.

```
nvidia-smi --query-gpu=utilization.gpu --format=csv -l 5                                                                                  
utilization.gpu [%]
[N/A]

```
As a result of `min(100, round(nvidia_gpu.gpu_util, 1))` the card always shows a 100% GPU usage.

`nvidia-settings`  show the GPU utilization correctly

```
nvidia-settings -c :0 -q '[gpu:0]/GPUUtilization' --terse                                                                              
graphics=32, memory=20, video=0, PCIe=2
```

It would be nice to have a fallback option to `nvidia-settings`

**Comment by PW999** [comment]
If interested, I could give a try implementing this.

**Comment by bkbilly** [comment]
I am not sure how to check if the result of the nvidia-smi is correct because I haven't had this issue, but I'd be happy if you could implement this.

**Comment by PW999** [comment]
I was thinking it would maybe cleaner to have seperate modules then. So instead of just gpu, it could be gpu_amd, gpu_nvidia_smi and gpu_nvidia_settings with a fallback of gpu to gpu_amd and gpu_nvidia_smi ?

**Comment by bkbilly** [comment]
It used to be like this, but I changed it to make it one module for all GPUs because it seemed easier to document and make it easier for the user to understand.

1. If you want, you can make a completely new module for the gpu_nvidia_settings and add it to the [excluded list](https://bkbilly.gitbook.io/lnxlink/setup#exclude-modules) on the **consts.py** file. The problem would be that the existing users will be affected.
2.  Another idea would be to create a new folder called for example `custom modules` that the user could download and add them [manually](https://bkbilly.gitbook.io/lnxlink/development#load-a-custom-module). 

I would recommend the 2nd approach, but it's up to you.

**Comment by PW999** [comment]
I went for the 2nd route and published my custom module: https://github.com/PW999/lnxlink_gpu_nvidia_settings

**Comment by bkbilly** [comment]
This is awesome!
Thanks for taking the time to implement this!
If you don't mind, I could add it on the documentation so that it's easier found.

I have a minor comment:
You could create different identifiers so that it won't interfere with the original gpu module.

**Comment by bkbilly** [comment]
I've added your module at the documentation. 
Thanks for your contribution to my project!

**Comment by bkbilly** [comment]
I got my hands on an older GPU, the GeForce GTX 660 which I installed the 450 driver.
I've updated the dev version of LNXlink which uses the nvidia-smi and falls back to nvidia-settings for the load if it finds a NaN value.

I chose to use only the GPU load because the rest of the of the nvidia-settings results were not correct.

**Comment by PW999** [comment]
Isn't it great how nvidia's own software doesn't play well with it's own hardware :sweat_smile: 

Luckily for me it works great _most of the times_, but I think the issues I'm having are mostly due to it running as a service (headless) which the nvidia-settings doesn't like. Restarting the service usually solves the problem, which makes it even more weird.

**Comment by bkbilly** [comment]
For me it doesn't work as a headless installation.
I've tried using XAUTHORITY as environment variable, but it still doesn't work.
How did you manage to get information from nvidia-settings without having an active DISPLAY?
